services:
  db:
    restart: always

  backend:
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    # Menggunakan Gunicorn untuk produksi
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 run:app

  frontend:
    build:
      context: ./frontend
      target: prod
      args:
        - VITE_API_BASE_URL=/api
        - VITE_APP_NAME=${VITE_APP_NAME}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=/api
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
