"""change_digital_activity_to_string

Revision ID: 1538e9818bab
Revises: c87e1a99d5a7
Create Date: 2026-04-21 00:34:56.573119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1538e9818bab'
down_revision = 'c87e1a99d5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digital_activities', schema=None) as batch_op:
        batch_op.alter_column('smartphone_duration_hours',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('social_media_access_count',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('social_media_duration_hours',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('course_count',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('task_count',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digital_activities', schema=None) as batch_op:
        batch_op.alter_column('task_count',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('course_count',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('social_media_duration_hours',
               existing_type=sa.String(length=50),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('social_media_access_count',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('smartphone_duration_hours',
               existing_type=sa.String(length=50),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
