"""create digital activities table

Revision ID: 382943a3e056
Revises: 1a11cac79ab6
Create Date: 2026-04-21 02:57:59.929384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382943a3e056'
down_revision = '1a11cac79ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(length=50), nullable=False),
    sa.Column('smartphone_duration_hours', sa.String(length=50), nullable=False),
    sa.Column('social_media_access_count', sa.String(length=50), nullable=False),
    sa.Column('social_media_duration_hours', sa.String(length=50), nullable=False),
    sa.Column('course_count', sa.String(length=50), nullable=False),
    sa.Column('task_count', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='uq_user_activity_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digital_activities')
    # ### end Alembic commands ###
