"""create physiological data table

Revision ID: 67433725ab6a
Revises: 4514d29a9086
Create Date: 2026-01-26 00:28:32.276635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67433725ab6a'
down_revision = '4514d29a9086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physiological_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('heart_rate_avg', sa.Integer(), nullable=False),
    sa.Column('heart_rate_min', sa.Integer(), nullable=False),
    sa.Column('heart_rate_max', sa.Integer(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('sleep_duration_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='uq_user_physio_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('physiological_data')
    # ### end Alembic commands ###
