"""add hrv_avg to physiological_data

Revision ID: 67515a21a0e3
Revises: 47e4aeac8379
Create Date: 2026-05-12 10:20:09.386185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67515a21a0e3'
down_revision = '47e4aeac8379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physiological_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hrv_avg', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physiological_data', schema=None) as batch_op:
        batch_op.drop_column('hrv_avg')

    # ### end Alembic commands ###
