"""add_pa_id_to_users

Revision ID: b7cbc0efe9ae
Revises: 2528981d5621
Create Date: 2026-04-13 14:04:41.058220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cbc0efe9ae'
down_revision = '2528981d5621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['pa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pa_id')

    # ### end Alembic commands ###
