"""add_day_type_to_digital_activities

Revision ID: c87e1a99d5a7
Revises: 5c5a023219c6
Create Date: 2026-04-21 00:20:37.725756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87e1a99d5a7'
down_revision = '5c5a023219c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digital_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digital_activities', schema=None) as batch_op:
        batch_op.drop_column('day_type')

    # ### end Alembic commands ###
