"""Add profile fields to User model

Revision ID: f20c4bceaf27
Revises: 041c26078309
Create Date: 2026-04-11 05:50:32.385484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20c4bceaf27'
down_revision = '041c26078309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('L', 'P', name='gender_enum'), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('university', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('major', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('residential_status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('residential_status')
        batch_op.drop_column('semester')
        batch_op.drop_column('major')
        batch_op.drop_column('university')
        batch_op.drop_column('age')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
